### ISSUE TITLE
Need a newer version of Pandoc for Mac users

### ISSUE THREAD

**Issue by DamienIrving** [carpentries/lesson-transition#102]
Following [step 1 of the transition guide](https://carpentries.github.io/sandpaper-docs/migrating-from-styles.html#workflow-setup), MacOS users will get the following error:
```
Pandoc binaries for arm64 on Mac are available for 3.1.2 and above only
```
I solved this problem by replacing all references to version 2.19.2 (e.g. `pandoc_activate("2.19.2")`) to reference version 3.1.2 instead.

**Comment by tobyhodges** [comment]
Closed by #96
