### ISSUE TITLE
datacarpentry/image-processing

### ISSUE THREAD

**Issue by zkamvar** [carpentries/lesson-transition#46]
tracking issues for <https://github.com/datacarpentry/image-processing>/

- [x] missing anchor (lesson-side) (https://github.com/datacarpentry/image-processing/pull/262)
- [x] extras link needs fixing
- [x] move `instructors/prereqs.md` to learners
- [x] setup in index needs to point to learners
- [x] 03-skimage-images.md
  - [x] Callout-box "Loading images with imageio: Read-only arrays": original markdown is missing a `>` (fixed in https://github.com/datacarpentry/image-processing/pull/271)
  - [x] Link "In [the Image Basics episode" and "[the Thresholding episode" has an extra `[`
- [x] 07-thresholding.md and 08-connected-components.md
  - [ ] alt text for images appearing in `{}` under some images

```markdown
episodes/02-image-basics.md:1004 [missing anchor]: [Accessing Metadata](#viewing-metadata)
index.md:23 [missing file]: [this detailed list](_extras/prereqs.md)
index.md:29 [missing file]: [make sure you have the software and data required](setup.md)
```

**Comment by uschille** [comment]
I noticed that on the [Summary and Setup](https://fishtree-attempt.github.io/image-processing/index.html) page some callout and solution blocks are not properly rendered.

**Comment by uschille** [comment]
I think the above is due to the formatting/indenting in the [original markdown](https://raw.githubusercontent.com/datacarpentry/image-processing/gh-pages/setup.md).

I found a few other similar things:
- [ ] 03-skimage-images.md
  * Callout-box "Loading images with imageio: Read-only arrays": original markdown is missing a `>`
  * Link "In [the Image Basics episode" has an extra `[`
- [ ] 07-thresholding.md and 08-connected-components.md
  * alt text for images appearing in `{}` under some images

These are my bad for not formatting the markdown properly...

There are few other links which have an extra `[` throughout the lesson.

I can fix these directly in the lesson after the transition.

Thanks for all the work @zkamvar! I'm impressed :raised_hands:

**Comment by zkamvar** [comment]
I've addressed these in https://github.com/carpentries/pegboard/pulls/121

The trailing alt text is partially a symptom of the fact that Kramdown is much more permissive than Pandoc.

**Comment by zkamvar** [comment]
> I noticed that on the [Summary and Setup](https://fishtree-attempt.github.io/image-processing/index.html) page some callout and solution blocks are not properly rendered.

I just figured out why this is not processing correctly: it's because the translated blocks have an indent of two spaces when they needed 3. I've fixed this issue in https://github.com/carpentries/lesson-transition/commit/17c55fcdc40e54f70c6160482173b55a745d2ca5. 

Note that the solutions blocks are now more buoyant (so they connect with the previous div and they may obscure some text. To prevent this, add an empty div like in https://github.com/swcarpentry/python-novice-inflammation/blob/5bee17dcf3f6416f949816fc5e2207935bd80330/learners/setup.md?plain=1#L44-L48:

```markdown
:::::::::::::::::::::::::::::::::::::::: {.empty-div style="margin-bottom: 50px"}


<!-- This div is intentionally empty to allow the solution to float alone-->


::::::::::::::::::::::::::::::::::::::::
```

**Comment by zkamvar** [comment]
A note about [the release of dc/image-processing](https://github.com/carpentries/lesson-transition/releases/tag/release_dc%2Fimage-processing)

We had technical issues with this release due to network errors. During
the push to main, we had the remote unexpectedly hang up.

To resolve this, Zhian manually ran the rest of the script starting from
where it left off (detailed below)

note that steps marked with (oops) are steps that Zhian should have
performed at a given time, but did later.

1. opened the `functions.R` file and scrolled to the definition for
   `setup_github()`
2. start R and run `source("functions.R")`
3. provision the five parameters
   - `path <- "release/datacarpentry/image-processing"`
   - `owner <- "datacarpentry"`
   - `repo <- "image-processing"`
   - `action <- "close-pr.yaml"` (oops)
   - `.token <- askpass::askpass()` and paste the release token (oops:
     several failed attempts with `system()` and `callr()`)
4. run lines [468 through 480](https://github.com/carpentries/lesson-transition/blob/release_dc/image-processing/functions.R#L468-L480)
5. run `default <- "gh-pages"` (because by then the default had changed)
6. run line [489](https://github.com/carpentries/lesson-transition/blob/release_dc/image-processing/functions.R#L489) (oops)
7. run lines [516 through 552](https://github.com/carpentries/lesson-transition/blob/release_dc/image-processing/functions.R#L516-L552) (force push and protect main branch)
9. run lines [555 through 576](https://github.com/carpentries/lesson-transition/blob/release_dc/image-processing/functions.R#L555-L576) (oops: see note 1)
10. run lines [516 through 552](https://github.com/carpentries/lesson-transition/blob/release_dc/image-processing/functions.R#L578-L604)

note 1: step 9 did not work because I had not previously set my `action`
variable. Thus, when it failed, it failed in a state where the gh-pages
branch was already checked out and cleaned, so it continued to fail on
`git rm -rf .`. I switched to the shell and manually added the action
file to the branch, staged, committed, and force-pushed _just_ in time
for it to be provisioned ahead of the build workflow.

This WAS a successful run, but it did require manual intervention.

**Comment by zkamvar** [comment]
This has been completed in 04a15709f82127820332bd2da5a0140300fdad75
